### ISSUE TITLE
Extensões para Clone() e/ou Copy()

### ISSUE THREAD

**Issue by VitorSouza23** [ghiorzi/pandemonium#9]
Fala tio Rodigo, como tu tá jovem?

Eu estava pensando em criar um fork do projeto **Pandemonium** para adicionar métodos de extensão de Clone() para a classe **Object** e Copy() para a interface **IEnumerable**.

Eu estava pensando em usar a **serialização** e **desserialização** para **JSON**, o que tu acha?

OBS: A ideia não é pensar em performance, mas sim em um atalho que ajude a criar uma cópia que não seja por referência, para que as alteração em um objeto não afete o outro (útil para logs de comparação de alteração).

**Comment by ghiorzi** [comment]
Fala tio vitas, beleza? Perdão pelo delay, não havia notado a notificação haha

Manda ver mano! Pretende usar o _System.Text.Json_? 

Outra alternativa seria por stream (_System.Runtime.Serialization_), porém acredito que a classe deva estar decorada com _**Serializable**_, se não deve dar treta. Por serialização é mais prático para o dev

Aguardo o seu PR e agradeço a contribuição desde já :)

**Comment by VitorSouza23** [comment]
Asudhaisuhduias tranquilo tio Rodrigo, vou dar uma estuda nas ideias que tu passou e ver qual a melhor pra implementar.

**Comment by VitorSouza23** [comment]
PR criado! Eu usei a estratégia de serialização por dois motivos:
 - _System.Text.Json_ só está disponível para .net core 3.1 e .net 5
-  Não quis instalar _Newtonsoft.Json_ para não poluir a biblioteca com outras bibliotecas e causar problemas de versão

Fique a vontade para fazer criticas e sugestões.

**Comment by ghiorzi** [comment]
Show, agradeço novamente a sua contribuição. Sinta-se livre para sugerir novas ideias

Os métodos estão disponíveis a partir da versão 2.2.0, a mesma já está publicada xD

**Comment by VitorSouza23** [comment]
Show tio Rodrigo! Obrigado pelo apoio!
